//! FIRE configuration frontend. Modelica semantics remain owned by the compiler.
pub mod artifact;
pub mod composition;
pub mod config;
pub mod lower;

pub type Result<T> = std::result::Result<T, String>;

pub const GENERATOR: &str = "fire_modelica_models/tools/fire-compose";
pub const HEADER: &str = "// Generated by fire_modelica_models/tools/fire-compose; do not edit.\n";
// Recognize existing generated outputs across the Modelica namespace rename.
pub const LEGACY_GENERATOR: &str = "FIRE_Modelica/tools/fire-compose";
pub const LEGACY_HEADER: &str = "// Generated by FIRE_Modelica/tools/fire-compose; do not edit.\n";

pub fn identifier(name: &str) -> bool {
    let mut chars = name.chars();
    matches!(chars.next(), Some(c) if c.is_ascii_alphabetic() || c == '_')
        && chars.all(|c| c.is_ascii_alphanumeric() || c == '_')
        && ![
            "and",
            "annotation",
            "break",
            "constrainedby",
            "der",
            "discrete",
            "each",
            "elseif",
            "elsewhen",
            "encapsulated",
            "enumeration",
            "expandable",
            "external",
            "final",
            "flow",
            "impure",
            "in",
            "initial",
            "inner",
            "not",
            "operator",
            "or",
            "outer",
            "partial",
            "protected",
            "public",
            "pure",
            "return",
            "stream",
            "type",
            "while",
            "model",
            "end",
            "within",
            "equation",
            "algorithm",
            "input",
            "output",
            "parameter",
            "constant",
            "Real",
            "Integer",
            "Boolean",
            "String",
            "time",
            "true",
            "false",
            "extends",
            "redeclare",
            "replaceable",
            "class",
            "record",
            "package",
            "connect",
            "if",
            "then",
            "else",
            "for",
            "loop",
            "when",
            "function",
            "block",
            "connector",
        ]
        .contains(&name)
}
