within fire_modelica_models.Adapters.FastDyn;
model MultirotorValueAdapter "Flat value boundary for host integration; not a firmware driver"
  parameter Vehicles.Copter.Geometry geometry;
  parameter Physical.Mechanical.Chassis.LandingGear.Parameters landingGear;
  parameter Real p_start[3]={0,0,-1};
  input Real pwm_us[geometry.nActuators];
  PwmDemand commands(nChannels=geometry.nActuators);
  Vehicles.Copter.MultirotorWithSensors vehicle(geometry=geometry,p_start=p_start,landingGear=landingGear);
  output Real acceleration_frd[3] "Specific force [m/s2]";
  output Real gyro_frd[3] "rad/s";
  output Real magneticField_frd[3] "T";
  output Real position_ned[3] "Local Cartesian; not latitude/longitude/altitude";
  output Real velocity_ned[3] "m/s";
  output Real pressure_Pa;
  output Real temperature_K;
  output Real altitude_m "Up positive";
  output Real climbRate_mps "Up positive";
  output Real rotorSpeed[geometry.nRotors] "rad/s; all mapped rotor channels";
  output Interfaces.VehicleState truth "Separate NED/FRD simulation truth";
equation
  commands.pulseWidth_us=pwm_us;
  vehicle.demand=commands.demand;
  acceleration_frd=geometry.R_bImu*vehicle.measurements.acceleration;
  gyro_frd=geometry.R_bImu*vehicle.measurements.gyro;
  magneticField_frd=geometry.R_bMag*vehicle.measurements.magneticField;
  position_ned=vehicle.measurements.position;
  velocity_ned=vehicle.measurements.velocity;
  pressure_Pa=vehicle.measurements.pressure;
  temperature_K=vehicle.measurements.temperature;
  altitude_m=vehicle.measurements.altitude;
  climbRate_mps=vehicle.measurements.climbRate;
  rotorSpeed=vehicle.rotors.rotorSpeed;
  truth=vehicle.truth;
end MultirotorValueAdapter;
