#!/usr/bin/env python3
"""Validate a bounded FIRE configuration and emit a numeric Modelica assembly.

Usage: python3 tools/generate_config.py configs/quad.toml [--check]
The generated class keeps the plant's demand input. --check runs checkModel,
not a simulation or a claim of deployment/physics verification.
Output directories must be under this repository's build directory or outside
the repository. Existing Modelica files require this generator's ownership header.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import math
from pathlib import Path
import re
import shutil
import subprocess
import tempfile

try:
    import tomllib
except ModuleNotFoundError:  # Python 3.10: pip install tomli
    import tomli as tomllib


ROOT = Path(__file__).resolve().parents[1]
GENERATOR_ID = "fire_modelica_models/tools/generate_config.py"
GENERATED_HEADER = "// Generated by " + GENERATOR_ID + "; do not edit.\n"
# Accept artifacts emitted before the Modelica namespace was renamed.
LEGACY_GENERATOR_ID = "FIRE_Modelica/tools/generate_config.py"
LEGACY_GENERATED_HEADER = "// Generated by " + LEGACY_GENERATOR_ID + "; do not edit.\n"
PRESETS = {"QuadX": (4, 4, .25), "HexaX": (6, 6, .30),
           "OctoX": (8, 8, .35), "CoaxialX8": (4, 8, .25)}
IDENTITY = [[1., 0., 0.], [0., 1., 0.], [0., 0., 1.]]


class ConfigError(ValueError):
    """Configuration is outside the explicitly supported initial profile."""


def table(value, allowed, path):
    if not isinstance(value, dict):
        raise ConfigError(f"{path}: expected a table")
    unknown = set(value) - set(allowed)
    if unknown:
        raise ConfigError(f"{path}: unknown fields {', '.join(sorted(unknown))}")
    return value


def number(value, path, *, positive=False, nonnegative=False):
    try:
        finite = math.isfinite(value)
    except (TypeError, OverflowError):
        finite = False
    if isinstance(value, bool) or not isinstance(value, (int, float)) or not finite:
        raise ConfigError(f"{path}: expected a finite number")
    if positive and value <= 0 or nonnegative and value < 0:
        raise ConfigError(f"{path}: expected {'positive' if positive else 'nonnegative'} value")
    return value


def integer(value, path, minimum=1):
    if type(value) is not int or value < minimum:
        raise ConfigError(f"{path}: expected integer >= {minimum}")
    return value


def array(value, shape, path):
    if not shape:
        return number(value, path)
    if not isinstance(value, list) or len(value) != shape[0]:
        raise ConfigError(f"{path}: expected dimensions {shape}")
    return [array(v, shape[1:], f"{path}[{i}]") for i, v in enumerate(value)]


def determinant(a):
    return (a[0][0] * (a[1][1] * a[2][2] - a[1][2] * a[2][1])
            - a[0][1] * (a[1][0] * a[2][2] - a[1][2] * a[2][0])
            + a[0][2] * (a[1][0] * a[2][1] - a[1][1] * a[2][0]))


def rotation(value, path):
    a = array(value, [3, 3], path)
    error = max(abs(sum(a[k][i] * a[k][j] for k in range(3)) - (i == j))
                for i in range(3) for j in range(3))
    if error > 1e-9 or abs(determinant(a) - 1) > 1e-9:
        raise ConfigError(f"{path}: expected an orthonormal rotation with determinant +1")
    return a


def inertia(value, path):
    a = array(value, [3, 3], path)
    scale = max(abs(x) for row in a for x in row)
    if max(abs(a[i][j] - a[j][i]) for i in range(3) for j in range(3)) > 1e-12 * max(scale, 1e-30):
        raise ConfigError(f"{path}: inertia must be symmetric")
    # Sylvester's criterion, scaled to avoid cubing dimensional magnitudes.
    if scale == 0:
        raise ConfigError(f"{path}: inertia must be positive definite")
    b = [[x / scale for x in row] for row in a]
    if b[0][0] <= 0 or b[0][0] * b[1][1] - b[0][1] * b[1][0] <= 0 or determinant(b) <= 0:
        raise ConfigError(f"{path}: inertia must be positive definite")
    # A physical inertia also requires J=trace(I)/2*identity-I to be PSD.
    # SPD of I alone permits impossible principal moments such as (1,1,3).
    half_trace = sum(b[i][i] for i in range(3)) / 2
    second = [[(half_trace if i == j else 0.) - b[i][j] for j in range(3)] for i in range(3)]
    minors = [second[i][i] for i in range(3)]
    minors.extend(second[i][i] * second[j][j] - second[i][j] * second[j][i]
                  for i in range(3) for j in range(i + 1, 3))
    minors.append(determinant(second))
    if min(minors) < -1e-10:
        raise ConfigError(f"{path}: inertia must represent a physical mass distribution (second moment must be positive semidefinite)")
    return a


def component_id(value, path):
    if not isinstance(value, str) or not re.fullmatch(r"[A-Za-z0-9_.:/-]{0,128}", value):
        raise ConfigError(f"{path}: expected at most 128 letters, digits, or _ . : / -")
    return value


def part(value, path, position=None):
    value = table(value, {"mass", "inertia", "r_C", "R_Cj", "componentId"}, path)
    if not {"mass", "inertia"} <= value.keys():
        raise ConfigError(f"{path}: mass and inertia are required")
    return {"mass": number(value["mass"], path + ".mass", positive=True),
            "inertia": inertia(value["inertia"], path + ".inertia"),
            "r_C": array(value.get("r_C", position or [0., 0., 0.]), [3], path + ".r_C"),
            "R_Cj": rotation(value.get("R_Cj", IDENTITY), path + ".R_Cj"),
            "componentId": component_id(value.get("componentId", ""), path + ".componentId")}


def per_rotor(value, count, path, *, positive=False):
    values = value if isinstance(value, list) else [value] * count
    values = array(values, [count], path)
    return [number(x, path, positive=positive, nonnegative=not positive) for x in values]


def validate(config):
    """Return a resolved configuration; never create files during validation."""
    table(config, {"schema_version", "model_name", "geometry", "mass", "motor",
                   "sensors", "initial", "ground"}, "config")
    if type(config.get("schema_version")) is not int or config["schema_version"] != 1:
        raise ConfigError("schema_version must be 1")
    name = config.get("model_name", "ConfiguredCopter")
    if not isinstance(name, str) or not re.fullmatch(r"[A-Z][A-Za-z0-9_]*", name):
        raise ConfigError("model_name must be a simple identifier starting with an uppercase letter")
    g = table(config.get("geometry", {}), {"preset", "nLegs", "nActuators", "actuatorIndex",
        "armMount", "rotorArmIndex", "rotorPosition_C", "R_br", "spinSign", "legPosition_C"}, "geometry")
    preset = g.get("preset", "QuadX")
    if not isinstance(preset, str) or preset not in PRESETS:
        raise ConfigError(f"geometry.preset must be one of {', '.join(PRESETS)}")
    na, nr, radius = PRESETS[preset]
    nl = integer(g.get("nLegs", 4), "geometry.nLegs", 0)
    nc = integer(g.get("nActuators", nr), "geometry.nActuators")
    mounts = [[radius * math.cos((2 * i + 1) * math.pi / na),
               radius * math.sin((2 * i + 1) * math.pi / na), 0.] for i in range(na)]
    mounts = array(g.get("armMount", mounts), [na, 3], "geometry.armMount")
    arm_indices = g.get("rotorArmIndex", [1 + i % na for i in range(nr)])
    actuator_indices = g.get("actuatorIndex", list(range(1, nr + 1)))
    for key, values, upper in (("rotorArmIndex", arm_indices, na), ("actuatorIndex", actuator_indices, nc)):
        array(values, [nr], "geometry." + key)
        for index in values:
            if integer(index, "geometry." + key) > upper:
                raise ConfigError(f"geometry.{key}: index {index} exceeds {upper}")
    positions = [[*mounts[index - 1][:2], mounts[index - 1][2] +
                  ((.025 if i < 4 else -.025) if preset == "CoaxialX8" else 0.)]
                 for i, index in enumerate(arm_indices)]
    spins = [1 if i % 2 == 0 else -1 for i in range(nr)]
    if preset == "CoaxialX8":
        spins[4:] = [-x for x in spins[4:]]
    spins = array(g.get("spinSign", spins), [nr], "geometry.spinSign")
    if any(type(x) is not int or abs(x) != 1 for x in spins):
        raise ConfigError("geometry.spinSign entries must be integers +1 or -1")
    rotations = array(g.get("R_br", [IDENTITY for _ in range(nr)]), [nr, 3, 3], "geometry.R_br")
    for i, r in enumerate(rotations):
        rotation(r, f"geometry.R_br[{i}]")
    legs = [[.18 * math.cos(2 * math.pi * i / nl + math.pi / 4),
             .18 * math.sin(2 * math.pi * i / nl + math.pi / 4), -.15] for i in range(nl)]
    geometry = {"nArms": na, "nRotors": nr, "nLegs": nl, "nActuators": nc,
        "armMount": mounts, "rotorArmIndex": arm_indices, "actuatorIndex": actuator_indices,
        "rotorPosition_C": array(g.get("rotorPosition_C", positions), [nr, 3], "geometry.rotorPosition_C"),
        "R_br": rotations, "spinSign": spins,
        "legPosition_C": array(g.get("legPosition_C", legs), [nl, 3], "geometry.legPosition_C")}

    m = table(config.get("mass", {}), {"mode", "aggregate", "core", "arm", "payloads", "additional_parts"}, "mass")
    mode = m.get("mode", "aggregate")
    if mode == "aggregate":
        if set(m) - {"mode", "aggregate"}:
            raise ConfigError("mass: constituent fields are not permitted in aggregate mode")
        mass = {"mode": mode, "aggregate": part(m.get("aggregate", {
            "mass": 1.5, "inertia": [[.02, 0., 0.], [0., .02, 0.], [0., 0., .04]]}), "mass.aggregate")}
    elif mode == "assembled":
        if "aggregate" in m or "core" not in m or "arm" not in m:
            raise ConfigError("mass: assembled mode requires core and arm, and forbids aggregate")
        # This bounded schema places each common arm's mass at half its mount vector.
        arm = table(m["arm"], {"mass", "inertia", "R_Cj", "componentIds"}, "mass.arm")
        arm_ids = arm.get("componentIds", [f"arm.{i + 1}" for i in range(na)])
        if not isinstance(arm_ids, list) or len(arm_ids) != na:
            raise ConfigError(f"mass.arm.componentIds: expected {na} entries")
        arm_shape = {key: value for key, value in arm.items() if key != "componentIds"}
        mass = {"mode": mode, "core": part(m["core"], "mass.core"),
                "arms": [part(dict(arm_shape, componentId=arm_ids[i]), f"mass.arm[{i}]",
                              [x / 2 for x in p]) for i, p in enumerate(mounts)]}
        for key in ("payloads", "additional_parts"):
            parts = m.get(key, [])
            if not isinstance(parts, list):
                raise ConfigError(f"mass.{key}: expected array of tables")
            mass[key] = [part(p, f"mass.{key}[{i}]") for i, p in enumerate(parts)]
        selected_parts = [mass["core"]] + mass["arms"] + mass["payloads"] + mass["additional_parts"]
        ids = [p["componentId"] for p in selected_parts if p["componentId"]]
        if len(ids) != len(set(ids)):
            raise ConfigError("mass: duplicate nonempty componentId in the assembled mass budget")
    else:
        raise ConfigError("mass.mode must be aggregate or assembled")

    motor = table(config.get("motor", {}), {"omegaMax", "tau", "kT", "kQ", "omega_start"}, "motor")
    motor = {k: per_rotor(motor.get(k, v), nr, "motor." + k, positive=k in {"omegaMax", "tau", "kT"})
             for k, v in {"omegaMax": 1000., "tau": .03, "kT": 1e-5, "kQ": 1.5e-7, "omega_start": 0.}.items()}
    if any(w > limit for w, limit in zip(motor["omega_start"], motor["omegaMax"])):
        raise ConfigError("motor.omega_start must not exceed omegaMax")
    sensor_defaults = {"imuSamplePeriod": .0025, "magnetometerSamplePeriod": .02,
                       "gnssSamplePeriod": .2, "barometerSamplePeriod": .02}
    sensors = table(config.get("sensors", {}), sensor_defaults, "sensors")
    sensors = {k: number(sensors.get(k, v), "sensors." + k, positive=True) for k, v in sensor_defaults.items()}
    initial_defaults = {"p_start": [0., 0., 1.], "v_start": [0., 0., 0.],
                        "q_start": [1., 0., 0., 0.], "omega_start": [0., 0., 0.]}
    initial = table(config.get("initial", {}), initial_defaults, "initial")
    initial = {k: array(initial.get(k, v), [len(v)], "initial." + k) for k, v in initial_defaults.items()}
    if math.hypot(*initial["q_start"]) <= 1e-12:
        raise ConfigError("initial.q_start must be nonzero")
    ground_defaults = {"legStiffness": 1500., "legDamping": 25., "tangentialDamping": 10., "frictionCoefficient": .6}
    ground = table(config.get("ground", {}), ground_defaults, "ground")
    ground = {k: number(ground.get(k, v), "ground." + k,
                       positive=k == "legStiffness", nonnegative=k != "legStiffness") for k, v in ground_defaults.items()}
    return {"schema_version": 1, "model_name": name, "preset": preset, "geometry": geometry,
            "mass": mass, "motor": motor, "sensors": sensors, "initial": initial, "ground": ground}


def literal(value):
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, list):
        return "{" + ",".join(literal(x) for x in value) + "}"
    if isinstance(value, str):
        return json.dumps(value)
    return str(value) if isinstance(value, int) else format(value, ".17g")


def record(name, values):
    return name + "(" + ",".join(k + "=" + literal(v) for k, v in values.items()) + ")"


def render(config):
    """Emit only known class names and validated numeric/Boolean/identity literals."""
    g = dict(config["geometry"])
    # The empty matrix literal {} is rank one; leave the record's [0,3] default in place.
    if g["nLegs"] == 0:
        del g["legPosition_C"]
    modifiers = ["geometry=" + record("fire_modelica_models.Vehicles.Copter.Geometry", g)]
    m = config["mass"]
    modifiers.append("useAssembledMass=" + literal(m["mode"] == "assembled"))
    if m["mode"] == "aggregate":
        modifiers.append("aggregate=" + record("fire_modelica_models.Physical.Mechanical.MassProperties", m["aggregate"]))
    else:
        modifiers.append("core=" + record("fire_modelica_models.Physical.Mechanical.Chassis.CenterBody.RigidCenterBody", m["core"]))
        for key, field, kind in (("arms", "arms", "fire_modelica_models.Physical.Mechanical.Chassis.Arms.RigidArm"),
                ("payloads", "payloads", "fire_modelica_models.Physical.Mechanical.Chassis.Payloads.FixedPayload"),
                ("additional_parts", "additionalParts", "fire_modelica_models.Physical.Mechanical.MassProperties")):
            if key != "arms":
                modifiers.append(("nPayloads" if key == "payloads" else "nAdditionalParts") + "=" + str(len(m[key])))
            if m[key]:
                modifiers.append(field + "={" + ",".join(record(kind, p) for p in m[key]) + "}")
    names = {"omegaMax": "omegaMax", "tau": "motorTau", "kT": "kT", "kQ": "kQ", "omega_start": "rotorSpeed_start"}
    modifiers.extend(names[k] + "=" + literal(v) for k, v in config["motor"].items())
    for section in ("sensors", "initial", "ground"):
        modifiers.extend(k + "=" + literal(v) for k, v in config[section].items())
    return (GENERATED_HEADER + "within;\nmodel " + config["model_name"] + "\n"
            "  // Generated numeric assembly. Inherited demand remains an external input.\n"
            "  extends fire_modelica_models.Vehicles.Copter.MultirotorWithSensors(\n    "
            + ",\n    ".join(modifiers) + ");\nend " + config["model_name"] + ";\n")


def output_paths(output_dir, name):
    """Reject source destinations and unrelated files before creating anything."""
    requested = Path(output_dir) if output_dir is not None else ROOT / "build" / "generated"
    try:
        destination = requested.resolve()
    except (OSError, RuntimeError) as error:
        raise ConfigError(f"Cannot resolve output directory: {error}") from error
    source_root = ROOT.resolve()
    # Compare against the literal build child of the resolved source root, not
    # build.resolve(): a build symlink into Vehicles must not whitelist Vehicles.
    if destination.is_relative_to(source_root) and not destination.is_relative_to(source_root / "build"):
        raise ConfigError("Output directory must be inside ROOT/build or outside the source root")
    if destination.exists() and not destination.is_dir():
        raise ConfigError("Output directory is not a directory")
    model_file = destination / (name + ".mo")
    manifest_file = destination / (name + ".manifest.json")
    for path in (model_file, manifest_file):
        if path.is_symlink():
            raise ConfigError(f"Refusing symlink output file: {path}")
        if path.exists() and not path.is_file():
            raise ConfigError(f"Output path is not a regular file: {path}")
    legacy_prefix = ("within;\nmodel " + name + "\n"
                     "  // Generated numeric assembly. Inherited demand remains an external input.\n")
    previous_model = None
    if model_file.exists():
        previous_model = model_file.read_text(encoding="utf-8")
        if not previous_model.startswith((GENERATED_HEADER, LEGACY_GENERATED_HEADER, legacy_prefix)):
            raise ConfigError(f"Refusing to overwrite non-generated Modelica file: {model_file}")
    if manifest_file.exists():
        try:
            previous = json.loads(manifest_file.read_text(encoding="utf-8"))
        except (ValueError, UnicodeError) as error:
            raise ConfigError(f"Refusing to overwrite non-generated manifest: {manifest_file}") from error
        owned = isinstance(previous, dict) and previous.get("generator_id") in (GENERATOR_ID, LEGACY_GENERATOR_ID)
        # Recognize earlier manifests only with their matching generated model.
        legacy_owned = (isinstance(previous, dict) and previous_model is not None
            and previous.get("manifest_version") == 1 and previous.get("target") == "openmodelica-native"
            and isinstance(previous.get("config"), dict)
            and previous.get("config", {}).get("model_name") == name
            and previous.get("generated_model_sha256") == hashlib.sha256(previous_model.encode()).hexdigest())
        if not owned and not legacy_owned:
            raise ConfigError(f"Refusing to overwrite non-generated manifest: {manifest_file}")
    return destination, model_file, manifest_file


def capture(command):
    try:
        result = subprocess.run(command, cwd=ROOT, capture_output=True, text=True, timeout=15, check=False)
        return result.stdout.strip() if result.returncode == 0 else None
    except (OSError, subprocess.TimeoutExpired):
        return None


def source_manifest():
    digest = hashlib.sha256()
    files = {}
    for path in sorted(ROOT.rglob("*.mo")):
        relative = path.relative_to(ROOT)
        if any(x in {"build", ".git", "__pycache__"} for x in relative.parts):
            continue
        contents = path.read_bytes()
        files[relative.as_posix()] = hashlib.sha256(contents).hexdigest()
        digest.update(relative.as_posix().encode() + b"\0" + contents + b"\0")
    status = capture(["git", "status", "--porcelain", "--untracked-files=normal"])
    return {"sha256": digest.hexdigest(), "files": files,
            "git_revision": capture(["git", "rev-parse", "HEAD"]),
            "git_dirty": None if status is None else bool(status)}


def check_model(executable, model_file, name):
    with tempfile.TemporaryDirectory(prefix="fire_config_check_") as work:
        script = Path(work) / "check.mos"
        script.write_text("loadModel(Modelica, {\"4.0.0\"});\nloadFile("
                          + json.dumps((ROOT / "package.mo").as_posix()) + ");\nloadFile("
                          + json.dumps(model_file.resolve().as_posix()) + ");\ncheckModel("
                          + name + ");\ngetErrorString();\n", encoding="utf-8")
        try:
            run = subprocess.run([executable, str(script)], cwd=work, capture_output=True,
                                 text=True, timeout=120, check=False)
        except (OSError, subprocess.TimeoutExpired) as error:
            raise ConfigError(f"OpenModelica check could not run: {error}") from error
        output = run.stdout + run.stderr
        if run.returncode != 0 or f"Check of {name} completed successfully." not in output or "Error:" in output:
            raise ConfigError("OpenModelica checkModel failed:\n" + output)
        return output


def generate(config_path, output_dir=None, *, compiler="omc", check=False):
    config_path = Path(config_path)
    raw = config_path.read_bytes()
    resolved = validate(tomllib.loads(raw.decode("utf-8")))
    model_text = render(resolved)
    destination, model_file, manifest_file = output_paths(output_dir, resolved["model_name"])
    executable = shutil.which(compiler)
    version = capture([executable, "--version"]) if executable else None
    if check and not executable:
        raise ConfigError(f"Compiler not found: {compiler}")
    manifest = {"generator_id": GENERATOR_ID, "manifest_version": 1, "schema_version": 1,
        "config_sha256": hashlib.sha256(raw).hexdigest(), "config": resolved,
        "source": source_manifest(), "generated_model_sha256": hashlib.sha256(model_text.encode()).hexdigest(),
        "compiler": {"requested": compiler, "executable": executable, "version": version},
        "target": "openmodelica-native",
        "declared_capabilities": ["N-rotor rigid body", "speed-lag and quadratic blade",
            "sampled value-level IMU/magnetometer/local-GNSS/barometer", "leg contact switching"],
        "excluded_capabilities": ["electrical power balance", "sensor protocols/registers", "firmware execution",
            "EMI", "blade flapping", "coaxial wake interaction"],
        "event_requirements": {"sampled_sensors": True, "ground_contact": resolved["geometry"]["nLegs"] > 0},
        "verification": {"schema": "passed", "openmodelica_checkModel": "not_run",
                         "simulation": "not_run", "deployment": "not_run"}}
    destination.mkdir(parents=True, exist_ok=True)
    model_file.write_text(model_text, encoding="utf-8")
    manifest_file.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    if check:
        try:
            check_model(executable, model_file, resolved["model_name"])
            manifest["verification"]["openmodelica_checkModel"] = "passed"
        except ConfigError:
            manifest["verification"]["openmodelica_checkModel"] = "failed"
            raise
        finally:
            manifest_file.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    return model_file, manifest_file


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("config", type=Path)
    parser.add_argument("--output-dir", type=Path)
    parser.add_argument("--compiler", default="omc")
    parser.add_argument("--check", action="store_true", help="Run OpenModelica checkModel; does not simulate")
    args = parser.parse_args()
    try:
        paths = generate(args.config, args.output_dir, compiler=args.compiler, check=args.check)
    except (ConfigError, OSError, UnicodeError, tomllib.TOMLDecodeError) as error:
        parser.exit(2, f"Configuration error: {error}\n")
    for path in paths:
        print(path)


if __name__ == "__main__":
    main()
